// Code generated by protoc-gen-go. DO NOT EDIT.
// source: codebender/qrcode/v1/qrcode_api.proto

package qrcodev1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateRequest struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateRequest) Reset()         { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()    {}
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b17bb0e58be216, []int{0}
}

func (m *GenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRequest.Unmarshal(m, b)
}
func (m *GenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRequest.Marshal(b, m, deterministic)
}
func (m *GenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRequest.Merge(m, src)
}
func (m *GenerateRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateRequest.Size(m)
}
func (m *GenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRequest proto.InternalMessageInfo

func (m *GenerateRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GenerateResponse struct {
	QrCode               []byte   `protobuf:"bytes,1,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateResponse) Reset()         { *m = GenerateResponse{} }
func (m *GenerateResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateResponse) ProtoMessage()    {}
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b17bb0e58be216, []int{1}
}

func (m *GenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateResponse.Unmarshal(m, b)
}
func (m *GenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateResponse.Marshal(b, m, deterministic)
}
func (m *GenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateResponse.Merge(m, src)
}
func (m *GenerateResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateResponse.Size(m)
}
func (m *GenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateResponse proto.InternalMessageInfo

func (m *GenerateResponse) GetQrCode() []byte {
	if m != nil {
		return m.QrCode
	}
	return nil
}

func init() {
	proto.RegisterType((*GenerateRequest)(nil), "codebender.qrcode.v1.GenerateRequest")
	proto.RegisterType((*GenerateResponse)(nil), "codebender.qrcode.v1.GenerateResponse")
}

func init() {
	proto.RegisterFile("codebender/qrcode/v1/qrcode_api.proto", fileDescriptor_86b17bb0e58be216)
}

var fileDescriptor_86b17bb0e58be216 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0xce, 0x4f, 0x49,
	0x4d, 0x4a, 0xcd, 0x4b, 0x49, 0x2d, 0xd2, 0x2f, 0x2c, 0x02, 0x71, 0xf4, 0xcb, 0x0c, 0xa1, 0xac,
	0xf8, 0xc4, 0x82, 0x4c, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x11, 0x84, 0x32, 0x3d, 0x88,
	0xa4, 0x5e, 0x99, 0xa1, 0x92, 0x2a, 0x17, 0xbf, 0x7b, 0x6a, 0x5e, 0x6a, 0x51, 0x62, 0x49, 0x6a,
	0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x10, 0x17, 0x4b, 0x4a, 0x62, 0x49, 0xa2, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xa4, 0xcd, 0x25, 0x80, 0x50, 0x56, 0x5c, 0x90,
	0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xce, 0xc5, 0x5e, 0x58, 0x14, 0x0f, 0x32, 0x08, 0xac, 0x94, 0x27,
	0x88, 0xad, 0xb0, 0xc8, 0x39, 0x3f, 0x25, 0xd5, 0x28, 0x8d, 0x8b, 0x33, 0x30, 0x08, 0xc4, 0x72,
	0x0c, 0xf0, 0x14, 0x8a, 0xe4, 0xe2, 0x80, 0xe9, 0x14, 0x52, 0xd5, 0xc3, 0xe6, 0x06, 0x3d, 0x34,
	0x07, 0x48, 0xa9, 0x11, 0x52, 0x06, 0x71, 0x80, 0x13, 0x57, 0x14, 0x07, 0x44, 0xb6, 0xcc, 0x30,
	0x89, 0x0d, 0xec, 0x49, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x08, 0x20, 0xa5, 0x0d,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QRCodeAPIClient is the client API for QRCodeAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QRCodeAPIClient interface {
	// Generate returns a QR image with the input encoded.
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type qRCodeAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewQRCodeAPIClient(cc grpc.ClientConnInterface) QRCodeAPIClient {
	return &qRCodeAPIClient{cc}
}

func (c *qRCodeAPIClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, "/codebender.qrcode.v1.QRCodeAPI/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QRCodeAPIServer is the server API for QRCodeAPI service.
type QRCodeAPIServer interface {
	// Generate returns a QR image with the input encoded.
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
}

// UnimplementedQRCodeAPIServer can be embedded to have forward compatible implementations.
type UnimplementedQRCodeAPIServer struct {
}

func (*UnimplementedQRCodeAPIServer) Generate(ctx context.Context, req *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}

func RegisterQRCodeAPIServer(s *grpc.Server, srv QRCodeAPIServer) {
	s.RegisterService(&_QRCodeAPI_serviceDesc, srv)
}

func _QRCodeAPI_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeAPIServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codebender.qrcode.v1.QRCodeAPI/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeAPIServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QRCodeAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "codebender.qrcode.v1.QRCodeAPI",
	HandlerType: (*QRCodeAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _QRCodeAPI_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "codebender/qrcode/v1/qrcode_api.proto",
}
